/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 13:50:29 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 13:50:29 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 13:50:29 +0000] [79] [INFO] Using worker: sync
[2025-08-10 13:50:29 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 13:50:29 +0000] [81] [INFO] Booting worker with pid: 81
[2025-08-10 13:50:31 +0000] [79] [INFO] Handling signal: term
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 13:57:13 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 13:57:13 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 13:57:13 +0000] [79] [INFO] Using worker: sync
[2025-08-10 13:57:13 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 13:57:13 +0000] [81] [INFO] Booting worker with pid: 81
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 10:58:07 -0300] [81] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:58:07 -0300] [81] [INFO] Worker exiting (pid: 81)
[2025-08-10 13:58:07 +0000] [269] [INFO] Booting worker with pid: 269
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 10:58:56 -0300] [80] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:58:56 -0300] [80] [INFO] Worker exiting (pid: 80)
[2025-08-10 13:58:56 +0000] [303] [INFO] Booting worker with pid: 303
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 10:59:29 -0300] [303] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:59:29 -0300] [303] [INFO] Worker exiting (pid: 303)
[2025-08-10 13:59:30 +0000] [337] [INFO] Booting worker with pid: 337
[2025-08-10 10:59:30 -0300] [269] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 10:59:30 -0300] [269] [INFO] Worker exiting (pid: 269)
[2025-08-10 13:59:31 +0000] [354] [INFO] Booting worker with pid: 354
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:04 -0300] [337] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:04 -0300] [337] [INFO] Worker exiting (pid: 337)
[2025-08-10 11:03:05 -0300] [354] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:05 -0300] [354] [INFO] Worker exiting (pid: 354)
[2025-08-10 14:03:05 +0000] [443] [INFO] Booting worker with pid: 443
[2025-08-10 14:03:05 +0000] [444] [INFO] Booting worker with pid: 444
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:12 -0300] [443] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:12 -0300] [443] [INFO] Worker exiting (pid: 443)
[2025-08-10 11:03:12 -0300] [444] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:12 -0300] [444] [INFO] Worker exiting (pid: 444)
[2025-08-10 14:03:13 +0000] [511] [INFO] Booting worker with pid: 511
[2025-08-10 14:03:13 +0000] [512] [INFO] Booting worker with pid: 512
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:15 -0300] [511] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 21, in <module>
    @receiver(post_save, sender=Organization)
NameError: name 'Organization' is not defined
[2025-08-10 11:03:15 -0300] [511] [INFO] Worker exiting (pid: 511)
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:15 -0300] [512] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 21, in <module>
    @receiver(post_save, sender=Organization)
NameError: name 'Organization' is not defined
[2025-08-10 11:03:15 -0300] [512] [INFO] Worker exiting (pid: 512)
[2025-08-10 14:03:15 +0000] [79] [WARNING] Worker with pid 512 was terminated due to signal 15
[2025-08-10 14:03:16 +0000] [79] [INFO] Shutting down: Master
[2025-08-10 14:03:16 +0000] [79] [INFO] Reason: Worker failed to boot.
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 14:03:17 +0000] [577] [INFO] Starting gunicorn 20.1.0
[2025-08-10 14:03:17 +0000] [577] [INFO] Listening at: http://0.0.0.0:8000 (577)
[2025-08-10 14:03:17 +0000] [577] [INFO] Using worker: sync
[2025-08-10 14:03:17 +0000] [578] [INFO] Booting worker with pid: 578
[2025-08-10 14:03:17 +0000] [579] [INFO] Booting worker with pid: 579
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:03:24 -0300] [578] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:24 -0300] [578] [INFO] Worker exiting (pid: 578)
[2025-08-10 11:03:24 -0300] [579] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:03:24 -0300] [579] [INFO] Worker exiting (pid: 579)
[2025-08-10 14:03:24 +0000] [646] [INFO] Booting worker with pid: 646
[2025-08-10 14:03:24 +0000] [647] [INFO] Booting worker with pid: 647
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:04:06 -0300] [646] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 11:04:06 -0300] [646] [INFO] Worker exiting (pid: 646)
[2025-08-10 11:04:06 -0300] [647] [INFO] Worker reloading: /app/src/apps/core/serializers.py modified
[2025-08-10 11:04:06 -0300] [647] [INFO] Worker exiting (pid: 647)
[2025-08-10 14:04:06 +0000] [714] [INFO] Booting worker with pid: 714
[2025-08-10 14:04:06 +0000] [715] [INFO] Booting worker with pid: 715
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 14:05:30 +0000] [577] [INFO] Handling signal: term
[2025-08-10 11:05:30 -0300] [715] [INFO] Worker exiting (pid: 715)
[2025-08-10 11:05:30 -0300] [714] [INFO] Worker exiting (pid: 714)
[2025-08-10 14:05:31 +0000] [577] [INFO] Shutting down: Master
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 14:10:26 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 14:10:26 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 14:10:26 +0000] [79] [INFO] Using worker: sync
[2025-08-10 14:10:26 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 14:10:26 +0000] [81] [INFO] Booting worker with pid: 81
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 14:14:26 +0000] [79] [INFO] Handling signal: term
[2025-08-10 11:14:26 -0300] [81] [INFO] Worker exiting (pid: 81)
[2025-08-10 11:14:26 -0300] [80] [INFO] Worker exiting (pid: 80)
[2025-08-10 14:14:26 +0000] [79] [INFO] Shutting down: Master
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 14:20:40 +0000] [79] [INFO] Starting gunicorn 20.1.0
[2025-08-10 14:20:40 +0000] [79] [INFO] Listening at: http://0.0.0.0:8000 (79)
[2025-08-10 14:20:40 +0000] [79] [INFO] Using worker: sync
[2025-08-10 14:20:40 +0000] [80] [INFO] Booting worker with pid: 80
[2025-08-10 14:20:40 +0000] [81] [INFO] Booting worker with pid: 81
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:21:14 -0300] [80] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:21:14 -0300] [80] [INFO] Worker exiting (pid: 80)
[2025-08-10 11:21:15 -0300] [81] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:21:15 -0300] [81] [INFO] Worker exiting (pid: 81)
[2025-08-10 14:21:15 +0000] [269] [INFO] Booting worker with pid: 269
[2025-08-10 14:21:15 +0000] [270] [INFO] Booting worker with pid: 270
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:23:50 -0300] [269] [INFO] Worker reloading: /app/src/apps/core/admin.py modified
[2025-08-10 11:23:50 -0300] [269] [INFO] Worker exiting (pid: 269)
[2025-08-10 14:23:50 +0000] [424] [INFO] Booting worker with pid: 424
[2025-08-10 11:23:51 -0300] [270] [INFO] Worker reloading: /app/src/apps/core/admin.py modified
[2025-08-10 11:23:51 -0300] [270] [INFO] Worker exiting (pid: 270)
[2025-08-10 14:23:51 +0000] [441] [INFO] Booting worker with pid: 441
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:23:58 -0300] [424] [INFO] Worker reloading: /app/src/apps/core/admin.py modified
[2025-08-10 11:23:58 -0300] [424] [INFO] Worker exiting (pid: 424)
[2025-08-10 11:23:59 -0300] [441] [INFO] Worker reloading: /app/src/apps/core/admin.py modified
[2025-08-10 11:23:59 -0300] [441] [INFO] Worker exiting (pid: 441)
[2025-08-10 14:23:59 +0000] [492] [INFO] Booting worker with pid: 492
[2025-08-10 14:23:59 +0000] [493] [INFO] Booting worker with pid: 493
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:49:13 -0300] [493] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:13 -0300] [493] [INFO] Worker exiting (pid: 493)
[2025-08-10 11:49:13 -0300] [492] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:13 -0300] [492] [INFO] Worker exiting (pid: 492)
[2025-08-10 14:49:14 +0000] [560] [INFO] Booting worker with pid: 560
[2025-08-10 14:49:14 +0000] [561] [INFO] Booting worker with pid: 561
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:49:17 -0300] [560] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:17 -0300] [560] [INFO] Worker exiting (pid: 560)
[2025-08-10 11:49:17 -0300] [561] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:17 -0300] [561] [INFO] Worker exiting (pid: 561)
[2025-08-10 14:49:18 +0000] [628] [INFO] Booting worker with pid: 628
[2025-08-10 14:49:18 +0000] [629] [INFO] Booting worker with pid: 629
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:49:24 -0300] [628] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:49:24 -0300] [628] [INFO] Worker exiting (pid: 628)
[2025-08-10 11:49:24 -0300] [629] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:49:24 -0300] [629] [INFO] Worker exiting (pid: 629)
[2025-08-10 14:49:25 +0000] [696] [INFO] Booting worker with pid: 696
[2025-08-10 14:49:25 +0000] [697] [INFO] Booting worker with pid: 697
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:49:27 -0300] [696] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
ImportError: cannot import name 'retrive_data' from 'apps.core.services' (/app/src/apps/core/services.py)
[2025-08-10 11:49:27 -0300] [696] [INFO] Worker exiting (pid: 696)
[2025-08-10 11:49:27 -0300] [697] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
ImportError: cannot import name 'retrive_data' from 'apps.core.services' (/app/src/apps/core/services.py)
[2025-08-10 11:49:27 -0300] [697] [INFO] Worker exiting (pid: 697)
[2025-08-10 14:49:28 +0000] [79] [WARNING] Worker with pid 697 was terminated due to signal 15
[2025-08-10 14:49:28 +0000] [79] [INFO] Shutting down: Master
[2025-08-10 14:49:28 +0000] [79] [INFO] Reason: Worker failed to boot.
/usr/local/lib/python3.10/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-08-10 14:49:29 +0000] [762] [INFO] Starting gunicorn 20.1.0
[2025-08-10 14:49:29 +0000] [762] [INFO] Listening at: http://0.0.0.0:8000 (762)
[2025-08-10 14:49:29 +0000] [762] [INFO] Using worker: sync
[2025-08-10 14:49:29 +0000] [763] [INFO] Booting worker with pid: 763
[2025-08-10 14:49:29 +0000] [764] [INFO] Booting worker with pid: 764
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:49:44 -0300] [763] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:44 -0300] [763] [INFO] Worker exiting (pid: 763)
[2025-08-10 11:49:44 -0300] [764] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:44 -0300] [764] [INFO] Worker exiting (pid: 764)
[2025-08-10 14:49:44 +0000] [831] [INFO] Booting worker with pid: 831
[2025-08-10 14:49:44 +0000] [832] [INFO] Booting worker with pid: 832
[2025-08-10 11:49:44 -0300] [831] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    organization = 
                   ^
SyntaxError: invalid syntax
[2025-08-10 11:49:44 -0300] [832] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    organization = 
                   ^
SyntaxError: invalid syntax
[2025-08-10 11:49:49 -0300] [831] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:49 -0300] [831] [INFO] Worker exiting (pid: 831)
[2025-08-10 11:49:49 -0300] [832] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:49:49 -0300] [832] [INFO] Worker exiting (pid: 832)
[2025-08-10 14:49:50 +0000] [835] [INFO] Booting worker with pid: 835
[2025-08-10 14:49:50 +0000] [836] [INFO] Booting worker with pid: 836
[2025-08-10 11:49:50 -0300] [835] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    organization = instance.
                            ^
SyntaxError: invalid syntax
[2025-08-10 11:49:50 -0300] [836] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    organization = instance.
                            ^
SyntaxError: invalid syntax
[2025-08-10 11:50:03 -0300] [835] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:03 -0300] [835] [INFO] Worker exiting (pid: 835)
[2025-08-10 11:50:03 -0300] [836] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:03 -0300] [836] [INFO] Worker exiting (pid: 836)
[2025-08-10 14:50:03 +0000] [839] [INFO] Booting worker with pid: 839
[2025-08-10 14:50:03 +0000] [840] [INFO] Booting worker with pid: 840
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:50:13 -0300] [839] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:13 -0300] [839] [INFO] Worker exiting (pid: 839)
[2025-08-10 11:50:13 -0300] [840] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:13 -0300] [840] [INFO] Worker exiting (pid: 840)
[2025-08-10 14:50:14 +0000] [907] [INFO] Booting worker with pid: 907
[2025-08-10 14:50:14 +0000] [908] [INFO] Booting worker with pid: 908
[2025-08-10 11:50:14 -0300] [907] [ERROR] invalid syntax (signals.py, line 20)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 20
    secret = 
             ^
SyntaxError: invalid syntax
[2025-08-10 11:50:14 -0300] [908] [ERROR] invalid syntax (signals.py, line 20)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 20
    secret = 
             ^
SyntaxError: invalid syntax
[2025-08-10 11:50:22 -0300] [907] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:22 -0300] [907] [INFO] Worker exiting (pid: 907)
[2025-08-10 11:50:22 -0300] [908] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:22 -0300] [908] [INFO] Worker exiting (pid: 908)
[2025-08-10 14:50:22 +0000] [911] [INFO] Booting worker with pid: 911
[2025-08-10 14:50:22 +0000] [912] [INFO] Booting worker with pid: 912
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:50:29 -0300] [911] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:29 -0300] [911] [INFO] Worker exiting (pid: 911)
[2025-08-10 11:50:29 -0300] [912] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:29 -0300] [912] [INFO] Worker exiting (pid: 912)
[2025-08-10 14:50:30 +0000] [979] [INFO] Booting worker with pid: 979
[2025-08-10 14:50:30 +0000] [980] [INFO] Booting worker with pid: 980
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:50:35 -0300] [979] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:35 -0300] [979] [INFO] Worker exiting (pid: 979)
[2025-08-10 11:50:35 -0300] [980] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:35 -0300] [980] [INFO] Worker exiting (pid: 980)
[2025-08-10 14:50:36 +0000] [1047] [INFO] Booting worker with pid: 1047
[2025-08-10 14:50:36 +0000] [1048] [INFO] Booting worker with pid: 1048
[2025-08-10 11:50:36 -0300] [1047] [ERROR] invalid syntax (signals.py, line 21)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 21
    repository = 
                 ^
SyntaxError: invalid syntax
[2025-08-10 11:50:36 -0300] [1048] [ERROR] invalid syntax (signals.py, line 21)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 21
    repository = 
                 ^
SyntaxError: invalid syntax
[2025-08-10 11:50:41 -0300] [1047] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:41 -0300] [1047] [INFO] Worker exiting (pid: 1047)
[2025-08-10 11:50:41 -0300] [1048] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:41 -0300] [1048] [INFO] Worker exiting (pid: 1048)
[2025-08-10 14:50:41 +0000] [1051] [INFO] Booting worker with pid: 1051
[2025-08-10 14:50:41 +0000] [1052] [INFO] Booting worker with pid: 1052
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:50:49 -0300] [1051] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:49 -0300] [1051] [INFO] Worker exiting (pid: 1051)
[2025-08-10 11:50:49 -0300] [1052] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:49 -0300] [1052] [INFO] Worker exiting (pid: 1052)
[2025-08-10 14:50:49 +0000] [1119] [INFO] Booting worker with pid: 1119
[2025-08-10 14:50:49 +0000] [1120] [INFO] Booting worker with pid: 1120
[2025-08-10 11:50:50 -0300] [1119] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    application = 
                  ^
SyntaxError: invalid syntax
[2025-08-10 11:50:50 -0300] [1120] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    application = 
                  ^
SyntaxError: invalid syntax
[2025-08-10 11:50:51 -0300] [1119] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:51 -0300] [1119] [INFO] Worker exiting (pid: 1119)
[2025-08-10 11:50:51 -0300] [1120] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:51 -0300] [1120] [INFO] Worker exiting (pid: 1120)
[2025-08-10 14:50:51 +0000] [1123] [INFO] Booting worker with pid: 1123
[2025-08-10 14:50:51 +0000] [1124] [INFO] Booting worker with pid: 1124
[2025-08-10 11:50:51 -0300] [1123] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    application = instance.
                           ^
SyntaxError: invalid syntax
[2025-08-10 11:50:51 -0300] [1124] [ERROR] invalid syntax (signals.py, line 19)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 19
    application = instance.
                           ^
SyntaxError: invalid syntax
[2025-08-10 11:50:56 -0300] [1123] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:56 -0300] [1123] [INFO] Worker exiting (pid: 1123)
[2025-08-10 11:50:56 -0300] [1124] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:50:56 -0300] [1124] [INFO] Worker exiting (pid: 1124)
[2025-08-10 14:50:56 +0000] [1127] [INFO] Booting worker with pid: 1127
[2025-08-10 14:50:57 +0000] [1128] [INFO] Booting worker with pid: 1128
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:03 -0300] [1127] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:03 -0300] [1127] [INFO] Worker exiting (pid: 1127)
[2025-08-10 11:51:03 -0300] [1128] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:03 -0300] [1128] [INFO] Worker exiting (pid: 1128)
[2025-08-10 14:51:04 +0000] [1195] [INFO] Booting worker with pid: 1195
[2025-08-10 14:51:04 +0000] [1196] [INFO] Booting worker with pid: 1196
[2025-08-10 11:51:04 -0300] [1195] [ERROR] invalid syntax (signals.py, line 23)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 23
    retrive_data(,instance.secret,instance.repository),
                 ^
SyntaxError: invalid syntax
[2025-08-10 11:51:04 -0300] [1196] [ERROR] invalid syntax (signals.py, line 23)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 23
    retrive_data(,instance.secret,instance.repository),
                 ^
SyntaxError: invalid syntax
[2025-08-10 11:51:06 -0300] [1195] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:06 -0300] [1195] [INFO] Worker exiting (pid: 1195)
[2025-08-10 11:51:06 -0300] [1196] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:06 -0300] [1196] [INFO] Worker exiting (pid: 1196)
[2025-08-10 14:51:06 +0000] [1199] [INFO] Booting worker with pid: 1199
[2025-08-10 14:51:06 +0000] [1200] [INFO] Booting worker with pid: 1200
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:11 -0300] [1199] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:11 -0300] [1199] [INFO] Worker exiting (pid: 1199)
[2025-08-10 11:51:11 -0300] [1200] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:11 -0300] [1200] [INFO] Worker exiting (pid: 1200)
[2025-08-10 14:51:12 +0000] [1267] [INFO] Booting worker with pid: 1267
[2025-08-10 14:51:12 +0000] [1268] [INFO] Booting worker with pid: 1268
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:16 -0300] [1267] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:16 -0300] [1267] [INFO] Worker exiting (pid: 1267)
[2025-08-10 11:51:16 -0300] [1268] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:16 -0300] [1268] [INFO] Worker exiting (pid: 1268)
[2025-08-10 14:51:17 +0000] [1335] [INFO] Booting worker with pid: 1335
[2025-08-10 14:51:17 +0000] [1336] [INFO] Booting worker with pid: 1336
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:20 -0300] [1335] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:20 -0300] [1335] [INFO] Worker exiting (pid: 1335)
[2025-08-10 11:51:20 -0300] [1336] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:20 -0300] [1336] [INFO] Worker exiting (pid: 1336)
[2025-08-10 14:51:21 +0000] [1403] [INFO] Booting worker with pid: 1403
[2025-08-10 14:51:21 +0000] [1404] [INFO] Booting worker with pid: 1404
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:24 -0300] [1404] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:24 -0300] [1404] [INFO] Worker exiting (pid: 1404)
[2025-08-10 11:51:24 -0300] [1403] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:24 -0300] [1403] [INFO] Worker exiting (pid: 1403)
[2025-08-10 14:51:25 +0000] [1471] [INFO] Booting worker with pid: 1471
[2025-08-10 14:51:25 +0000] [1472] [INFO] Booting worker with pid: 1472
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:33 -0300] [1471] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:51:33 -0300] [1472] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:51:33 -0300] [1472] [INFO] Worker exiting (pid: 1472)
[2025-08-10 11:51:33 -0300] [1471] [INFO] Worker exiting (pid: 1471)
[2025-08-10 14:51:33 +0000] [1539] [INFO] Booting worker with pid: 1539
[2025-08-10 14:51:33 +0000] [1540] [INFO] Booting worker with pid: 1540
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:37 -0300] [1539] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:51:37 -0300] [1540] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:51:37 -0300] [1540] [INFO] Worker exiting (pid: 1540)
[2025-08-10 11:51:37 -0300] [1539] [INFO] Worker exiting (pid: 1539)
[2025-08-10 14:51:37 +0000] [1607] [INFO] Booting worker with pid: 1607
[2025-08-10 14:51:38 +0000] [1608] [INFO] Booting worker with pid: 1608
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:44 -0300] [1607] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:44 -0300] [1607] [INFO] Worker exiting (pid: 1607)
[2025-08-10 11:51:44 -0300] [1608] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:44 -0300] [1608] [INFO] Worker exiting (pid: 1608)
[2025-08-10 14:51:45 +0000] [1675] [INFO] Booting worker with pid: 1675
[2025-08-10 14:51:45 +0000] [1676] [INFO] Booting worker with pid: 1676
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:51:58 -0300] [1675] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:58 -0300] [1675] [INFO] Worker exiting (pid: 1675)
[2025-08-10 11:51:58 -0300] [1676] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:51:58 -0300] [1676] [INFO] Worker exiting (pid: 1676)
[2025-08-10 14:51:58 +0000] [1743] [INFO] Booting worker with pid: 1743
[2025-08-10 14:51:58 +0000] [1744] [INFO] Booting worker with pid: 1744
[2025-08-10 11:51:58 -0300] [1743] [ERROR] invalid syntax (signals.py, line 23)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 23
    retrive_data(application=application, organization=organization, secret=secret, user=repository=repository),
                                                                                                   ^
SyntaxError: invalid syntax
[2025-08-10 11:51:58 -0300] [1744] [ERROR] invalid syntax (signals.py, line 23)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 23
    retrive_data(application=application, organization=organization, secret=secret, user=repository=repository),
                                                                                                   ^
SyntaxError: invalid syntax
[2025-08-10 11:52:07 -0300] [1743] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:07 -0300] [1743] [INFO] Worker exiting (pid: 1743)
[2025-08-10 11:52:07 -0300] [1744] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:07 -0300] [1744] [INFO] Worker exiting (pid: 1744)
[2025-08-10 14:52:07 +0000] [1747] [INFO] Booting worker with pid: 1747
[2025-08-10 14:52:07 +0000] [1748] [INFO] Booting worker with pid: 1748
[2025-08-10 11:52:07 -0300] [1747] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=repository=repository),
                                                                                                   ^
SyntaxError: invalid syntax
[2025-08-10 11:52:07 -0300] [1748] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=repository=repository),
                                                                                                   ^
SyntaxError: invalid syntax
[2025-08-10 11:52:17 -0300] [1747] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:17 -0300] [1747] [INFO] Worker exiting (pid: 1747)
[2025-08-10 11:52:17 -0300] [1748] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:17 -0300] [1748] [INFO] Worker exiting (pid: 1748)
[2025-08-10 14:52:17 +0000] [1751] [INFO] Booting worker with pid: 1751
[2025-08-10 14:52:17 +0000] [1752] [INFO] Booting worker with pid: 1752
[2025-08-10 11:52:18 -0300] [1751] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=ruserepository=repository),
                                                                                                       ^
SyntaxError: invalid syntax
[2025-08-10 11:52:18 -0300] [1752] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=ruserepository=repository),
                                                                                                       ^
SyntaxError: invalid syntax
[2025-08-10 11:52:20 -0300] [1751] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:20 -0300] [1751] [INFO] Worker exiting (pid: 1751)
[2025-08-10 11:52:20 -0300] [1752] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:20 -0300] [1752] [INFO] Worker exiting (pid: 1752)
[2025-08-10 14:52:20 +0000] [1755] [INFO] Booting worker with pid: 1755
[2025-08-10 14:52:20 +0000] [1756] [INFO] Booting worker with pid: 1756
[2025-08-10 11:52:20 -0300] [1755] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=userepository=repository),
                                                                                                      ^
SyntaxError: invalid syntax
[2025-08-10 11:52:20 -0300] [1756] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=userepository=repository),
                                                                                                      ^
SyntaxError: invalid syntax
[2025-08-10 11:52:21 -0300] [1756] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:21 -0300] [1756] [INFO] Worker exiting (pid: 1756)
[2025-08-10 14:52:21 +0000] [1759] [INFO] Booting worker with pid: 1759
[2025-08-10 11:52:22 -0300] [1759] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=userrepository=repository),
                                                                                                       ^
SyntaxError: invalid syntax
[2025-08-10 11:52:22 -0300] [1755] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:22 -0300] [1755] [INFO] Worker exiting (pid: 1755)
[2025-08-10 14:52:22 +0000] [1761] [INFO] Booting worker with pid: 1761
[2025-08-10 11:52:23 -0300] [1761] [ERROR] invalid syntax (signals.py, line 24)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 24
    retrive_data(application=application, organization=organization, secret=secret, user=userrepository=repository),
                                                                                                       ^
SyntaxError: invalid syntax
[2025-08-10 11:52:24 -0300] [1761] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:24 -0300] [1761] [INFO] Worker exiting (pid: 1761)
[2025-08-10 11:52:24 -0300] [1759] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:24 -0300] [1759] [INFO] Worker exiting (pid: 1759)
[2025-08-10 14:52:24 +0000] [1763] [INFO] Booting worker with pid: 1763
[2025-08-10 14:52:24 +0000] [1764] [INFO] Booting worker with pid: 1764
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:52:27 -0300] [1763] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:27 -0300] [1763] [INFO] Worker exiting (pid: 1763)
[2025-08-10 11:52:27 -0300] [1764] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:27 -0300] [1764] [INFO] Worker exiting (pid: 1764)
[2025-08-10 14:52:28 +0000] [1831] [INFO] Booting worker with pid: 1831
[2025-08-10 14:52:28 +0000] [1832] [INFO] Booting worker with pid: 1832
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:52:31 -0300] [1831] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:31 -0300] [1831] [INFO] Worker exiting (pid: 1831)
[2025-08-10 11:52:31 -0300] [1832] [INFO] Worker reloading: /app/src/apps/core/signals.py modified
[2025-08-10 11:52:31 -0300] [1832] [INFO] Worker exiting (pid: 1832)
[2025-08-10 14:52:32 +0000] [1899] [INFO] Booting worker with pid: 1899
[2025-08-10 14:52:32 +0000] [1900] [INFO] Booting worker with pid: 1900
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:52:41 -0300] [1899] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:52:41 -0300] [1899] [INFO] Worker exiting (pid: 1899)
[2025-08-10 11:52:41 -0300] [1900] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:52:41 -0300] [1900] [INFO] Worker exiting (pid: 1900)
[2025-08-10 14:52:41 +0000] [1967] [INFO] Booting worker with pid: 1967
[2025-08-10 14:52:41 +0000] [1968] [INFO] Booting worker with pid: 1968
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:52:47 -0300] [1967] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:52:47 -0300] [1967] [INFO] Worker exiting (pid: 1967)
[2025-08-10 11:52:47 -0300] [1968] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:52:47 -0300] [1968] [INFO] Worker exiting (pid: 1968)
[2025-08-10 14:52:48 +0000] [2035] [INFO] Booting worker with pid: 2035
[2025-08-10 14:52:48 +0000] [2036] [INFO] Booting worker with pid: 2036
[2025-08-10 11:52:48 -0300] [2035] [ERROR] expected ':' (services.py, line 4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 4
    if application
                  ^
SyntaxError: expected ':'
[2025-08-10 11:52:48 -0300] [2036] [ERROR] expected ':' (services.py, line 4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 4
    if application
                  ^
SyntaxError: expected ':'
[2025-08-10 11:53:18 -0300] [2035] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:18 -0300] [2035] [INFO] Worker exiting (pid: 2035)
[2025-08-10 11:53:18 -0300] [2036] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:18 -0300] [2036] [INFO] Worker exiting (pid: 2036)
[2025-08-10 14:53:19 +0000] [2039] [INFO] Booting worker with pid: 2039
[2025-08-10 14:53:19 +0000] [2040] [INFO] Booting worker with pid: 2040
[2025-08-10 11:53:19 -0300] [2039] [ERROR] expected ':' (services.py, line 4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 4
    if application.lower()
                          ^
SyntaxError: expected ':'
[2025-08-10 11:53:19 -0300] [2040] [ERROR] expected ':' (services.py, line 4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 4
    if application.lower()
                          ^
SyntaxError: expected ':'
[2025-08-10 11:53:24 -0300] [2039] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:24 -0300] [2039] [INFO] Worker exiting (pid: 2039)
[2025-08-10 11:53:24 -0300] [2040] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:24 -0300] [2040] [INFO] Worker exiting (pid: 2040)
[2025-08-10 14:53:24 +0000] [2043] [INFO] Booting worker with pid: 2043
[2025-08-10 14:53:24 +0000] [2044] [INFO] Booting worker with pid: 2044
[2025-08-10 11:53:24 -0300] [2043] [ERROR] expected ':' (services.py, line 4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 4
    if application.lower()=="github"
                                    ^
SyntaxError: expected ':'
[2025-08-10 11:53:24 -0300] [2044] [ERROR] expected ':' (services.py, line 4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 4
    if application.lower()=="github"
                                    ^
SyntaxError: expected ':'
[2025-08-10 11:53:27 -0300] [2043] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:27 -0300] [2043] [INFO] Worker exiting (pid: 2043)
[2025-08-10 11:53:27 -0300] [2044] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:27 -0300] [2044] [INFO] Worker exiting (pid: 2044)
[2025-08-10 14:53:28 +0000] [2047] [INFO] Booting worker with pid: 2047
[2025-08-10 14:53:28 +0000] [2048] [INFO] Booting worker with pid: 2048
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:53:43 -0300] [2047] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:43 -0300] [2047] [INFO] Worker exiting (pid: 2047)
[2025-08-10 11:53:43 -0300] [2048] [INFO] Worker reloading: /app/src/apps/core/services.py modified
[2025-08-10 11:53:43 -0300] [2048] [INFO] Worker exiting (pid: 2048)
[2025-08-10 14:53:43 +0000] [2115] [INFO] Booting worker with pid: 2115
[2025-08-10 14:53:43 +0000] [2116] [INFO] Booting worker with pid: 2116
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:54:15 -0300] [2115] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:15 -0300] [2115] [INFO] Worker exiting (pid: 2115)
[2025-08-10 11:54:15 -0300] [2116] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:15 -0300] [2116] [INFO] Worker exiting (pid: 2116)
[2025-08-10 14:54:15 +0000] [2183] [INFO] Booting worker with pid: 2183
[2025-08-10 14:54:15 +0000] [2184] [INFO] Booting worker with pid: 2184
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:54:25 -0300] [2183] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:25 -0300] [2183] [INFO] Worker exiting (pid: 2183)
[2025-08-10 11:54:25 -0300] [2184] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:25 -0300] [2184] [INFO] Worker exiting (pid: 2184)
[2025-08-10 14:54:25 +0000] [2251] [INFO] Booting worker with pid: 2251
[2025-08-10 14:54:26 +0000] [2252] [INFO] Booting worker with pid: 2252
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:54:36 -0300] [2251] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:36 -0300] [2251] [INFO] Worker exiting (pid: 2251)
[2025-08-10 11:54:36 -0300] [2252] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:36 -0300] [2252] [INFO] Worker exiting (pid: 2252)
[2025-08-10 14:54:37 +0000] [2319] [INFO] Booting worker with pid: 2319
[2025-08-10 14:54:37 +0000] [2320] [INFO] Booting worker with pid: 2320
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:54:40 -0300] [2319] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:40 -0300] [2319] [INFO] Worker exiting (pid: 2319)
[2025-08-10 11:54:40 -0300] [2320] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:40 -0300] [2320] [INFO] Worker exiting (pid: 2320)
[2025-08-10 14:54:41 +0000] [2387] [INFO] Booting worker with pid: 2387
[2025-08-10 14:54:41 +0000] [2388] [INFO] Booting worker with pid: 2388
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:54:44 -0300] [2387] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:44 -0300] [2387] [INFO] Worker exiting (pid: 2387)
[2025-08-10 11:54:44 -0300] [2388] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:54:44 -0300] [2388] [INFO] Worker exiting (pid: 2388)
[2025-08-10 14:54:45 +0000] [2455] [INFO] Booting worker with pid: 2455
[2025-08-10 14:54:45 +0000] [2456] [INFO] Booting worker with pid: 2456
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:00 -0300] [2455] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:00 -0300] [2455] [INFO] Worker exiting (pid: 2455)
[2025-08-10 11:55:00 -0300] [2456] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:00 -0300] [2456] [INFO] Worker exiting (pid: 2456)
[2025-08-10 14:55:00 +0000] [2523] [INFO] Booting worker with pid: 2523
[2025-08-10 14:55:00 +0000] [2524] [INFO] Booting worker with pid: 2524
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:05 -0300] [2523] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:05 -0300] [2523] [INFO] Worker exiting (pid: 2523)
[2025-08-10 11:55:05 -0300] [2524] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:05 -0300] [2524] [INFO] Worker exiting (pid: 2524)
[2025-08-10 14:55:05 +0000] [2591] [INFO] Booting worker with pid: 2591
[2025-08-10 14:55:05 +0000] [2592] [INFO] Booting worker with pid: 2592
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:18 -0300] [2591] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:18 -0300] [2591] [INFO] Worker exiting (pid: 2591)
[2025-08-10 11:55:19 -0300] [2592] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:19 -0300] [2592] [INFO] Worker exiting (pid: 2592)
[2025-08-10 14:55:19 +0000] [2659] [INFO] Booting worker with pid: 2659
[2025-08-10 14:55:19 +0000] [2660] [INFO] Booting worker with pid: 2660
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:27 -0300] [2659] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:27 -0300] [2659] [INFO] Worker exiting (pid: 2659)
[2025-08-10 11:55:28 -0300] [2660] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:28 -0300] [2660] [INFO] Worker exiting (pid: 2660)
[2025-08-10 14:55:28 +0000] [2727] [INFO] Booting worker with pid: 2727
[2025-08-10 14:55:28 +0000] [2728] [INFO] Booting worker with pid: 2728
[2025-08-10 11:55:28 -0300] [2727] [ERROR] invalid syntax (extract_base.py, line 34)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 34
    organization:str, secret:str, repository:str
                    ^
SyntaxError: invalid syntax
[2025-08-10 11:55:28 -0300] [2728] [ERROR] invalid syntax (extract_base.py, line 34)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 34
    organization:str, secret:str, repository:str
                    ^
SyntaxError: invalid syntax
[2025-08-10 11:55:31 -0300] [2727] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:31 -0300] [2727] [INFO] Worker exiting (pid: 2727)
[2025-08-10 11:55:31 -0300] [2728] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:31 -0300] [2728] [INFO] Worker exiting (pid: 2728)
[2025-08-10 14:55:31 +0000] [2731] [INFO] Booting worker with pid: 2731
[2025-08-10 14:55:32 +0000] [2732] [INFO] Booting worker with pid: 2732
[2025-08-10 11:55:32 -0300] [2731] [ERROR] invalid syntax (extract_base.py, line 35)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 35
    secret:str, repository:str
              ^
SyntaxError: invalid syntax
[2025-08-10 11:55:32 -0300] [2732] [ERROR] invalid syntax (extract_base.py, line 35)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 35
    secret:str, repository:str
              ^
SyntaxError: invalid syntax
[2025-08-10 11:55:34 -0300] [2731] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:34 -0300] [2731] [INFO] Worker exiting (pid: 2731)
[2025-08-10 11:55:34 -0300] [2732] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:34 -0300] [2732] [INFO] Worker exiting (pid: 2732)
[2025-08-10 14:55:34 +0000] [2735] [INFO] Booting worker with pid: 2735
[2025-08-10 14:55:34 +0000] [2736] [INFO] Booting worker with pid: 2736
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:41 -0300] [2735] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:41 -0300] [2735] [INFO] Worker exiting (pid: 2735)
[2025-08-10 11:55:41 -0300] [2736] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:41 -0300] [2736] [INFO] Worker exiting (pid: 2736)
[2025-08-10 14:55:41 +0000] [2803] [INFO] Booting worker with pid: 2803
[2025-08-10 14:55:41 +0000] [2804] [INFO] Booting worker with pid: 2804
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:48 -0300] [2803] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:48 -0300] [2803] [INFO] Worker exiting (pid: 2803)
[2025-08-10 11:55:48 -0300] [2804] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:48 -0300] [2804] [INFO] Worker exiting (pid: 2804)
[2025-08-10 14:55:48 +0000] [2871] [INFO] Booting worker with pid: 2871
[2025-08-10 14:55:48 +0000] [2872] [INFO] Booting worker with pid: 2872
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:53 -0300] [2871] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:53 -0300] [2871] [INFO] Worker exiting (pid: 2871)
[2025-08-10 11:55:53 -0300] [2872] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:53 -0300] [2872] [INFO] Worker exiting (pid: 2872)
[2025-08-10 14:55:53 +0000] [2939] [INFO] Booting worker with pid: 2939
[2025-08-10 14:55:54 +0000] [2940] [INFO] Booting worker with pid: 2940
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:55:57 -0300] [2939] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:57 -0300] [2939] [INFO] Worker exiting (pid: 2939)
[2025-08-10 11:55:57 -0300] [2940] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:55:57 -0300] [2940] [INFO] Worker exiting (pid: 2940)
[2025-08-10 14:55:58 +0000] [3007] [INFO] Booting worker with pid: 3007
[2025-08-10 14:55:58 +0000] [3008] [INFO] Booting worker with pid: 3008
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:56:04 -0300] [3007] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:04 -0300] [3007] [INFO] Worker exiting (pid: 3007)
[2025-08-10 11:56:04 -0300] [3008] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:04 -0300] [3008] [INFO] Worker exiting (pid: 3008)
[2025-08-10 14:56:05 +0000] [3075] [INFO] Booting worker with pid: 3075
[2025-08-10 14:56:05 +0000] [3076] [INFO] Booting worker with pid: 3076
[2025-08-10 11:56:05 -0300] [3075] [ERROR] invalid syntax (extract_base.py, line 43)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 43
    self.
         ^
SyntaxError: invalid syntax
[2025-08-10 11:56:05 -0300] [3076] [ERROR] invalid syntax (extract_base.py, line 43)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 43
    self.
         ^
SyntaxError: invalid syntax
[2025-08-10 11:56:06 -0300] [3075] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:06 -0300] [3075] [INFO] Worker exiting (pid: 3075)
[2025-08-10 11:56:06 -0300] [3076] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:06 -0300] [3076] [INFO] Worker exiting (pid: 3076)
[2025-08-10 14:56:06 +0000] [3079] [INFO] Booting worker with pid: 3079
[2025-08-10 14:56:06 +0000] [3080] [INFO] Booting worker with pid: 3080
[2025-08-10 11:56:07 -0300] [3079] [ERROR] invalid syntax (extract_base.py, line 43)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 43
    self.organization = or
                        ^^
SyntaxError: invalid syntax
[2025-08-10 11:56:07 -0300] [3080] [ERROR] invalid syntax (extract_base.py, line 43)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 43
    self.organization = or
                        ^^
SyntaxError: invalid syntax
[2025-08-10 11:56:09 -0300] [3079] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:09 -0300] [3079] [INFO] Worker exiting (pid: 3079)
[2025-08-10 11:56:09 -0300] [3080] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:09 -0300] [3080] [INFO] Worker exiting (pid: 3080)
[2025-08-10 14:56:09 +0000] [3083] [INFO] Booting worker with pid: 3083
[2025-08-10 14:56:09 +0000] [3084] [INFO] Booting worker with pid: 3084
[2025-08-10 11:56:09 -0300] [3083] [ERROR] invalid syntax (extract_base.py, line 44)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 44
    self.
         ^
SyntaxError: invalid syntax
[2025-08-10 11:56:09 -0300] [3084] [ERROR] invalid syntax (extract_base.py, line 44)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 44
    self.
         ^
SyntaxError: invalid syntax
[2025-08-10 11:56:17 -0300] [3083] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:17 -0300] [3083] [INFO] Worker exiting (pid: 3083)
[2025-08-10 11:56:17 -0300] [3084] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:17 -0300] [3084] [INFO] Worker exiting (pid: 3084)
[2025-08-10 14:56:17 +0000] [3087] [INFO] Booting worker with pid: 3087
[2025-08-10 14:56:18 +0000] [3088] [INFO] Booting worker with pid: 3088
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:56:28 -0300] [3087] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:28 -0300] [3087] [INFO] Worker exiting (pid: 3087)
[2025-08-10 11:56:28 -0300] [3088] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:28 -0300] [3088] [INFO] Worker exiting (pid: 3088)
[2025-08-10 14:56:29 +0000] [3155] [INFO] Booting worker with pid: 3155
[2025-08-10 14:56:29 +0000] [3156] [INFO] Booting worker with pid: 3156
[2025-08-10 11:56:29 -0300] [3155] [ERROR] invalid syntax (extract_base.py, line 57)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 57
    self.token = 
                 ^
SyntaxError: invalid syntax
[2025-08-10 11:56:29 -0300] [3156] [ERROR] invalid syntax (extract_base.py, line 57)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 57
    self.token = 
                 ^
SyntaxError: invalid syntax
[2025-08-10 11:56:32 -0300] [3155] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:32 -0300] [3155] [INFO] Worker exiting (pid: 3155)
[2025-08-10 11:56:32 -0300] [3156] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:32 -0300] [3156] [INFO] Worker exiting (pid: 3156)
[2025-08-10 14:56:32 +0000] [3159] [INFO] Booting worker with pid: 3159
[2025-08-10 14:56:32 +0000] [3160] [INFO] Booting worker with pid: 3160
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:56:45 -0300] [3159] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:45 -0300] [3159] [INFO] Worker exiting (pid: 3159)
[2025-08-10 11:56:45 -0300] [3160] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:45 -0300] [3160] [INFO] Worker exiting (pid: 3160)
[2025-08-10 14:56:46 +0000] [3227] [INFO] Booting worker with pid: 3227
[2025-08-10 14:56:46 +0000] [3228] [INFO] Booting worker with pid: 3228
[2025-08-10 11:56:46 -0300] [3227] [ERROR] invalid syntax (extract_base.py, line 66)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 66
    repositories = self.
                        ^
SyntaxError: invalid syntax
[2025-08-10 11:56:46 -0300] [3228] [ERROR] invalid syntax (extract_base.py, line 66)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 66
    repositories = self.
                        ^
SyntaxError: invalid syntax
[2025-08-10 11:56:47 -0300] [3227] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:47 -0300] [3227] [INFO] Worker exiting (pid: 3227)
[2025-08-10 11:56:47 -0300] [3228] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:47 -0300] [3228] [INFO] Worker exiting (pid: 3228)
[2025-08-10 14:56:47 +0000] [3231] [INFO] Booting worker with pid: 3231
[2025-08-10 14:56:47 +0000] [3232] [INFO] Booting worker with pid: 3232
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:56:56 -0300] [3231] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:56 -0300] [3231] [INFO] Worker exiting (pid: 3231)
[2025-08-10 11:56:56 -0300] [3232] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:56:56 -0300] [3232] [INFO] Worker exiting (pid: 3232)
[2025-08-10 14:56:57 +0000] [3299] [INFO] Booting worker with pid: 3299
[2025-08-10 14:56:57 +0000] [3300] [INFO] Booting worker with pid: 3300
[2025-08-10 11:56:57 -0300] [3299] [ERROR] invalid syntax (extract_base.py, line 78)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 78
    organization_id = 
                      ^
SyntaxError: invalid syntax
[2025-08-10 11:56:57 -0300] [3300] [ERROR] invalid syntax (extract_base.py, line 78)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 78
    organization_id = 
                      ^
SyntaxError: invalid syntax
[2025-08-10 11:57:00 -0300] [3299] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:00 -0300] [3299] [INFO] Worker exiting (pid: 3299)
[2025-08-10 11:57:00 -0300] [3300] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:00 -0300] [3300] [INFO] Worker exiting (pid: 3300)
[2025-08-10 14:57:00 +0000] [3303] [INFO] Booting worker with pid: 3303
[2025-08-10 14:57:00 +0000] [3304] [INFO] Booting worker with pid: 3304
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:57:48 -0300] [3304] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:48 -0300] [3303] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:48 -0300] [3304] [INFO] Worker exiting (pid: 3304)
[2025-08-10 11:57:48 -0300] [3303] [INFO] Worker exiting (pid: 3303)
[2025-08-10 14:57:48 +0000] [3371] [INFO] Booting worker with pid: 3371
[2025-08-10 14:57:48 +0000] [3372] [INFO] Booting worker with pid: 3372
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:57:53 -0300] [3372] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:53 -0300] [3372] [INFO] Worker exiting (pid: 3372)
[2025-08-10 14:57:53 +0000] [3439] [INFO] Booting worker with pid: 3439
[2025-08-10 11:57:54 -0300] [3439] [ERROR] invalid syntax (extract_base.py, line 374)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 2, in <module>
    from .extract_base import ExtractBase  # noqa: I001
  File "/app/src/apps/core/extract_github/extract_base.py", line 374
    organization_name = 
                        ^
SyntaxError: invalid syntax
[2025-08-10 11:57:54 -0300] [3371] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:54 -0300] [3371] [INFO] Worker exiting (pid: 3371)
[2025-08-10 14:57:54 +0000] [3441] [INFO] Booting worker with pid: 3441
[2025-08-10 11:57:55 -0300] [3439] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:57:55 -0300] [3439] [INFO] Worker exiting (pid: 3439)
[2025-08-10 14:57:55 +0000] [3442] [INFO] Booting worker with pid: 3442
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:58:05 -0300] [3442] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:58:05 -0300] [3442] [INFO] Worker exiting (pid: 3442)
[2025-08-10 14:58:05 +0000] [3509] [INFO] Booting worker with pid: 3509
[2025-08-10 11:58:05 -0300] [3441] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:58:05 -0300] [3441] [INFO] Worker exiting (pid: 3441)
[2025-08-10 14:58:06 +0000] [3526] [INFO] Booting worker with pid: 3526
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:58:18 -0300] [3526] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:58:18 -0300] [3526] [INFO] Worker exiting (pid: 3526)
[2025-08-10 11:58:18 -0300] [3509] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_base.py modified
[2025-08-10 11:58:18 -0300] [3509] [INFO] Worker exiting (pid: 3509)
[2025-08-10 14:58:18 +0000] [3577] [INFO] Booting worker with pid: 3577
[2025-08-10 14:58:18 +0000] [3578] [INFO] Booting worker with pid: 3578
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:58:29 -0300] [3577] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:29 -0300] [3577] [INFO] Worker exiting (pid: 3577)
[2025-08-10 11:58:29 -0300] [3578] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:29 -0300] [3578] [INFO] Worker exiting (pid: 3578)
[2025-08-10 14:58:30 +0000] [3645] [INFO] Booting worker with pid: 3645
[2025-08-10 14:58:30 +0000] [3646] [INFO] Booting worker with pid: 3646
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:58:34 -0300] [3645] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:34 -0300] [3645] [INFO] Worker exiting (pid: 3645)
[2025-08-10 11:58:35 -0300] [3646] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:35 -0300] [3646] [INFO] Worker exiting (pid: 3646)
[2025-08-10 14:58:35 +0000] [3713] [INFO] Booting worker with pid: 3713
[2025-08-10 14:58:35 +0000] [3714] [INFO] Booting worker with pid: 3714
[2025-08-10 11:58:35 -0300] [3713] [ERROR] invalid syntax (extract_eo.py, line 21)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 21
    super().__init__(organization=organization, secret=)
                                                       ^
SyntaxError: invalid syntax
[2025-08-10 11:58:35 -0300] [3714] [ERROR] invalid syntax (extract_eo.py, line 21)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/dashboard/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/src/apps/core/apps.py", line 8, in ready
    import apps.core.signals
  File "/app/src/apps/core/signals.py", line 3, in <module>
    from .services import retrive_data
  File "/app/src/apps/core/services.py", line 1, in <module>
    from .tasks import retrieve_github_data, setup_periodic_tasks
  File "/app/src/apps/core/tasks.py", line 4, in <module>
    from .extract_github.extract_eo import ExtractEO
  File "/app/src/apps/core/extract_github/extract_eo.py", line 21
    super().__init__(organization=organization, secret=)
                                                       ^
SyntaxError: invalid syntax
[2025-08-10 11:58:38 -0300] [3713] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:38 -0300] [3713] [INFO] Worker exiting (pid: 3713)
[2025-08-10 11:58:38 -0300] [3714] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:38 -0300] [3714] [INFO] Worker exiting (pid: 3714)
[2025-08-10 14:58:38 +0000] [3717] [INFO] Booting worker with pid: 3717
[2025-08-10 14:58:39 +0000] [3718] [INFO] Booting worker with pid: 3718
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:58:45 -0300] [3717] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:45 -0300] [3717] [INFO] Worker exiting (pid: 3717)
[2025-08-10 11:58:45 -0300] [3718] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_eo.py modified
[2025-08-10 11:58:45 -0300] [3718] [INFO] Worker exiting (pid: 3718)
[2025-08-10 14:58:45 +0000] [3785] [INFO] Booting worker with pid: 3785
[2025-08-10 14:58:46 +0000] [3786] [INFO] Booting worker with pid: 3786
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:59:01 -0300] [3785] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_ciro.py modified
[2025-08-10 11:59:01 -0300] [3785] [INFO] Worker exiting (pid: 3785)
[2025-08-10 11:59:01 -0300] [3786] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_ciro.py modified
[2025-08-10 11:59:01 -0300] [3786] [INFO] Worker exiting (pid: 3786)
[2025-08-10 14:59:02 +0000] [3853] [INFO] Booting worker with pid: 3853
[2025-08-10 14:59:02 +0000] [3854] [INFO] Booting worker with pid: 3854
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:59:14 -0300] [3853] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_ciro.py modified
[2025-08-10 11:59:14 -0300] [3853] [INFO] Worker exiting (pid: 3853)
[2025-08-10 11:59:14 -0300] [3854] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_ciro.py modified
[2025-08-10 11:59:14 -0300] [3854] [INFO] Worker exiting (pid: 3854)
[2025-08-10 14:59:14 +0000] [3921] [INFO] Booting worker with pid: 3921
[2025-08-10 14:59:14 +0000] [3922] [INFO] Booting worker with pid: 3922
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:59:25 -0300] [3921] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_cmpo.py modified
[2025-08-10 11:59:25 -0300] [3921] [INFO] Worker exiting (pid: 3921)
[2025-08-10 11:59:25 -0300] [3922] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_cmpo.py modified
[2025-08-10 11:59:25 -0300] [3922] [INFO] Worker exiting (pid: 3922)
[2025-08-10 14:59:25 +0000] [3989] [INFO] Booting worker with pid: 3989
[2025-08-10 14:59:25 +0000] [3990] [INFO] Booting worker with pid: 3990
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-08-10 11:59:31 -0300] [3989] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_cmpo.py modified
[2025-08-10 11:59:31 -0300] [3989] [INFO] Worker exiting (pid: 3989)
[2025-08-10 11:59:31 -0300] [3990] [INFO] Worker reloading: /app/src/apps/core/extract_github/extract_cmpo.py modified
[2025-08-10 11:59:31 -0300] [3990] [INFO] Worker exiting (pid: 3990)
[2025-08-10 14:59:31 +0000] [4057] [INFO] Booting worker with pid: 4057
[2025-08-10 14:59:31 +0000] [4058] [INFO] Booting worker with pid: 4058
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
UserWarning: You have an incompatible version of 'pyarrow' installed (21.0.0), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
